### ISSUE TITLE
sls env list 

### ISSUE THREAD

**Issue by AdrienLemaire** [martinlindenberg/serverless-plugin-alerting#13]
The README documentation suggests the command `sls env list`, but I do not have such command available (I basically check with sls dash summary).

Using serverless 0.5.5. Has this feature been removed ? If yes, you might want to update the README.

Thanks for this great plugin, just what I needed!

**Comment by martinlindenberg** [comment]
i've replaced the `sls env list` with `sls variables list`

thanks for your comment
