### ISSUE TITLE
Feature request: Easy hook to send message into sns topic

### ISSUE THREAD

**Issue by jayzalowitz** [martinlindenberg/serverless-plugin-alerting#6]
It would be really awesome to have this (or perhaps another package altogether) send a notification to a sns topic so i can keep my lambda functions under 5 minutes by doing a fan out pattern on the event.

**Comment by martinlindenberg** [comment]
I think i don't understand your feature request.

do you need something like a wrapper for this function ?
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SNS.html#publish-property

**Comment by martinlindenberg** [comment]
two weeks without any explanation... 
closed

please add a new ticket if this feature is still required
